# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# this github action publishes a new integration version
# it also includes any overrides present in overrides.json and config-vars files.
# this sample is using the example in samples/scaffold-example

name: apply-sample-action
permissions: read-all

# Controls when the workflow will run
on: push

env:
  ENVIRONMENT: ${{ vars.ENVIRONMENT }}
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  REGION: ${{ vars.REGION }}
  WORKLOAD_IDENTITY_PROVIDER_NAME: ${{ vars.PROVIDER_NAME }}
  SERVICE_ACCOUNT: ${{ vars.SERVICE_ACCOUNT }}

jobs:

  integrationcli-action:

    permissions:
      contents: 'read'
      id-token: 'write'

    name: Apply integration version
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 #v4

      - name: Authenticate Google Cloud
        id: 'gcp-auth'
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f #v2.1.7
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER_NAME }}'
          service_account: '${{ env.SERVICE_ACCOUNT }}'
          token_format: 'access_token'

      - name: Calculate variables
        id: 'calc-vars'
        run: |
          echo "SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT

      - name: Install dependencies and integrationcli
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext-base curl
      
          # Download and install integrationcli
          curl -L https://raw.githubusercontent.com/GoogleCloudPlatform/application-integration-management-toolkit/main/downloadLatest.sh | sh -
      
          # Copy from non-root path (GitHub Actions runs as non-root)
          mkdir -p ./bin
          cp -r $HOME/.integrationcli/bin/* ./bin
      
          # Add to PATH
          echo "$PWD/bin" >> $GITHUB_PATH
          export PATH=$PATH:./bin
      
          # Check version
          ./bin/integrationcli --version
      
      - name: Detect Changed Integration Files
        id: detect-changes
        run: |
          echo "Finding changed integration files..."
      
          BASE_COMMIT="${{ github.event.before }}"
      
          if ! git cat-file -e "$BASE_COMMIT^{commit}" 2>/dev/null; then
            echo "Base commit not found, using fallback (initial commit)"
            CHANGED_FILES=$(git ls-files src/*.json)
          else
            echo "Using commit diff from $BASE_COMMIT to ${{ github.sha }}"
            CHANGED_FILES=$(git diff --name-only "$BASE_COMMIT" "${{ github.sha }}" | grep '^src/.*\.json$' || true)
          fi
      
          echo "CHANGED_FILES<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      

      - name: Deploy Changed Integrations
        if: steps.detect-changes.outputs.CHANGED_FILES != ''
        run: |
          echo "Detected changed integration files:"
          echo "${{ steps.detect-changes.outputs.CHANGED_FILES }}"
          
          for file in ${{ steps.detect-changes.outputs.CHANGED_FILES }}; do
            folder=$(dirname "$file")
            echo "Deploying integration from: $folder"
            
            ./bin/integrationcli integrations apply \
              --env=${{ env.ENVIRONMENT }} \
              --folder="$folder" \
              --userlabel=${{ steps.calc-vars.outputs.SHORT_SHA }} \
              --run-tests=true \
              --wait=true \
              --proj=${{ env.PROJECT_ID }} \
              --reg=${{ env.REGION }} \
              --token ${{ steps.gcp-auth.outputs.access_token }}
          done
